#!/usr/bin/env python3

import os


globals().update(config)

target_files = [Path(file_name)]


envvars:
    "BPA_APIKEY",


rule download_file:
    output:
        file=Path(file_name),
    params:
        url=bioplatforms_url,
        bpi_apikey=os.environ.get("BPA_APIKEY"),
    shell:
        "wget "
        '--header="X-CKAN-API-Key:{params.bpi_apikey}" '
        "-O {output.file} "
        "{params.url}"


if file_checksum:
    check_file = Path(file_name + ".check.txt")
    target_files.append(check_file)

    rule checksum:
        input:
            file=Path(file_name),
        output:
            check=check_file,
        params:
            file_checksum=file_checksum,
        shell:
            "printf '%s %s' {params.file_checksum}  {input.file} "
            "| md5sum -c - "
            "&> {output.check}"


rule target:
    default_target: True
    input:
        target_files,
